/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package overlappingIntervals;
import utils.Timer;
import utils.Out;
public class OverlappingIntervals {

    public static void main(String[] args) {
	//OverlappingInterval1D oi = new OverlappingInterval1D();
	//oi.initAndTest();
	Out out = new Out();
	Timer t = new Timer();
	OverlappingIntervals2D oi2d = new OverlappingIntervals2D();

	t.start();
	oi2d.initAndTest();
	t.end();
	out.println(t.toString());

    }
}

