/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package arrays;
import java.util.List;

import utils.In;
import utils.Out;
public class Arrays {

    public static void main(String[] args) {
	In in = new In();
	List<Integer> list = in.getListOfInteger("../resources/randomIntegers.md");
	//Stack<Integer> st = new Stack<Integer>();
	LinkedListQueue<Integer> st = new LinkedListQueue<Integer>();
	for(int i=0; i<list.size(); i++){
		st.enqueue(list.get(i));
	}
	Out out = new Out();
	out.println(st.toString());
	int d = st.dequeue();
	out.println(d);
	out.println(st.toString());

    }
}

