/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package timeTester;

public class TimeTester {

    public static void main(String[] args) {
	    TimeTesterDoubleSize tt = new TimeTesterDoubleSize();
	    tt.test();
    }
}

