/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ciclingRotation;
import utils.Out;
import utils.In;
import utils.Timer;
public class CiclingRotation {

    public static void main(String[] args) {
	Timer t = new Timer();
	CiclingRotationFinder rf = new CiclingRotationFinder();
	//rf.checkIndexOf("AFHEFAUPEAT", "FAUPEATAFHE");
	//rf.checkIndexOf("AFHEFAUPEAT", "FAUPEATAFHE");
	In in = new In();
	String randomLetters = in.fromFile("../resources/randomLetters.md");
	String randomLettersShifted = in.fromFile("../resources/randomLettersShifted.md");
	t.start();
	rf.checkCursorControl(randomLetters, randomLettersShifted);
	t.end();
	Out out = new Out();
	out.println(t.toString());

    }
}

