/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ciclingRotation;
public class CiclingRotation {

    public static void main(String[] args) {
	   CiclingRotationFinder rf = new CiclingRotationFinder();
	   //rf.checkIndexOf("AFHEFAUPEAT", "FAUPEATAFHE");
	   rf.checkIndexOf("AFHEFAUPEAT", "FAUPEATAFHE");
    }
}

