/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package searchers;
import java.util.Collections;
import java.util.List;

import utils.Convertor;
import utils.In;
import utils.Out;
import utils.Timer;
public class Searchers {

    public static void main(String[] args) {
	Convertor c = new Convertor();
	In in = new In();
	Out out = new Out();
	Timer t = new Timer();
	String readString = in.fromFile("../resources/randomIntegers.md");
	List<Integer> list = c.stringToListOfIntegers(readString);

	Integer indexOfValue;
	BruteForceSearcher bfs = new BruteForceSearcher();
	t.start();
	indexOfValue = bfs.search(list, 756);
	t.stop();
	out.log("BruteForce: " + indexOfValue + " " + t.toString());
	BinarySearcher bs = new BinarySearcher();
	t.start();
	Collections.sort(list);
	indexOfValue = bs.search(list, 756, 0, list.size());
	t.stop();
	out.log("BinarySearch: " + indexOfValue + " " + t.toString());

    }
}

