/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package resourcesCreator;

public class ResourcesCreator {

    public static void main(String[] args) {
	//FilesWithRandomLettersCreator fwrl = new FilesWithRandomLettersCreator();
	//FilesWithRandomDoublesCreator fwrd = new FilesWithRandomDoublesCreator();
	FilesWithRandomIntegersCreator fwri = new FilesWithRandomIntegersCreator();
	fwri.create();
	//fwrl.shift();
    }
}

