/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package utils;

public class Utils {

    public static void main(String[] args) {
	//ListInitilizer<Point> li = new ListInitilizer<>(Point.class);
	//List<Point> list = li.create(100); 
	//System.out.println(list.size());
	//ListInitilizerPoints lp = new ListInitilizerPoints();
	//List<Point> list = lp.generate(100);
	//System.out.println(list.size());
	//ListInitilizerPoints lp = new ListInitilizerPoints();
	//List<Point> list = lp.generate(100);
	System.out.println("Hello");
	



    }
}

