/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parenthesisCompletor;
import arrays.Stack;
import utils.Out;
import utils.In;
public class ParenthesisCompletor {

	public static void main(String[] args) {
		In in = new In();
		String s = in.fromFile("../resources/incompleteParenthesis.md");
		String[] dataArray = s.split(" ");
	
		TreeBuilder treeBuilder = new TreeBuilder(dataArray);
		treeBuilder.build();
	}
}

